language: ruby
dist: trusty
services:
- docker
rvm:
- 2.4.0
branches:
  only:
  - master
  - develop
  - "/^greenkeeper\\/.*$/"
before_deploy:
- pip install --upgrade --user awscli
deploy:
  - provider: script
    script: "./deploy/deploy.sh $STAGING_CLUSTER_STACK $STAGING_APP_STACK $STAGING_REPOSITORY_NAME $STAGING_DESIRED_COUNT"
    on:
      branch: develop
  - provider: script
    script: "./deploy/deploy.sh $PROD_CLUSTER_STACK $PROD_APP_STACK $PROD_REPOSITORY_NAME $PROD_DESIRED_COUNT"
    on:
      branch: production
notifications:
  slack:
    rooms:
      secure: LThaWUbmBm4rhpQT9WdeaWepI+FLLXED3j/FnH2DdDe2bQC25nWjos5SrepzrDLp42uM/WupCIqjlEXcQOUxdF9+9v+02dvsUFBtr8YpFyHPtiy6AJ3QpTYWxZd/J9FfeaIl29nu4hEXqkRDDToJOhl87alyPlYAiNIubgzBrDikt+UDB5IPgBrMUEyviG2selO+uWEOLgnTAMF2RRqtDuNiOiFXMYPWNxcx6Zf9UYcHdxd2DjtTAj4ts70dMpY93HTf71sxxkYy0EPsjh2T7miN/3QYG3HJfHDsJswzh4s0Y9vwXHHqZbiSsVKIJHg6Co8hHSVSMKU1VVOoy6bKsdPwTgXNQdYIeEBqEt8cUAWc4Z6kzayjrsvvIyVnyWvp6Wu4cb3KzbPaT5qSFB5zsREFZjY6rt4TU9KRLeNYAVKbrWrKAcKxLoV0clKl7J9NCe6ZK4K6b//RyS8ZNExcTafui7GmT4739ztbwh4P9VL0eTepdSzA6UjoAjv/lklMJex1b81oWUX10z+DdZrENAg8+YToGauJQGvqVvrCsiAN9NBWUq8Yoq++saZ1aAPIKqnoWGap1lHHko/LNMhi1XdurKsUi5idjsiWNatK8qKjLGaa2kDJpqb1VCJkXMo8BnaSYU8fMO9t2/2mzDsTV4RHzroK1hBDu5JJubj3YWc=
