dist: trusty
services:
- docker
addons:
- chrome: beta
language: node_js
env:
- TZ=America/New_York
git:
  depth: false
branches:
  only:
  - develop
before_install:
- npm install -g yarn@`jq -r .engines.yarn package.json`
stages:
- name: test
  if: branch !~ /^staging\//
jobs:
  include:
  - stage: test
    if: type IN (push)
    install:
    - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
    - yarn install --frozen-lockfile --ignore-scripts
    - yarn run prepare
    script:
    - yarn run test
    - yarn run test:templates
    after_failure:
    - artifacts upload --target-paths travis/screenshots/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID services-js/*/screenshots
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - lerna exec --stream --scope @cityofboston/deploy-tools report-updated-services
      on:
        branch: develop
  - if: type IN (pull_request)
    install:
    - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
    - yarn install --frozen-lockfile --ignore-scripts
    - lerna run --stream --since $TRAVIS_PULL_REQUEST_SHA^1 --include-filtered-dependencies 
      prepare
    script:
    - yarn run test:since $TRAVIS_PULL_REQUEST_SHA^1
    - yarn run test:templates:since $TRAVIS_PULL_REQUEST_SHA^1
    after_failure:
    - artifacts upload --target-paths travis/screenshots/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID services-js/*/screenshots
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: nCdLrImWYdmlid3Ij4S7tguVr9EhzvolsHhuUMq3M4x2pP2pvQa+amUEdsBwfOpoCWfd8LWSRIY5eoK7V361yHXYOR9484p2ny1o4/QDSTgtaEFhkBQlfYMvhTZrFZN8slCh2J30gbyvCW23fSpZIAkX3u8MPnGNHduee+lmTtfvKx9phrfLKJBko5kI+4gnOelLMFM0tjjmS4EXRbwhvYsPPwoMuPNOGoYQJAoUsH2WBRMizVMIc/Rtl/L2y0tQ8kBi0KtyEllHZO9ce1RoxFDMuRZzQnd2WsQ13ZN83e4qHeXQYDsLqVjRvjeENoM4RSUROplwTcrJ+AhOamUlSldPrgZYYYSEW4FI61fs4+zwJIP4/vCQk8b6IFA7DVAQz4pXUrZV6NuVZQmtZyTZth7UHIgDpepgFRcBI4tRZQ7W6XhPjGe/6xg0wZ/5K86HdZJG0Tq4B/tDLbu3y069Y2oKZYtCJebFYx45lF3iBCJx/97uJFcclB1rjyg8K0IGjCaraR6BatfLKKkrjg3bfzG643/AupWvYhsqg9Q6LFMtE1kucXmAEYRH/a58MmUjNYFavqsDNPVZ8xi1LEXp171ySd4agaHN/9+ORi2wectIgBZqOldGw80WXeLqP3lfVyRFtW26ZTpoM7jfxbzWiIpX4C7K4QHe4KAy8KTCnQ4=
