// flow-typed signature: de84c4f1a722f093ac791f5263dfce0a
// flow-typed version: <<STUB>>/gl_vx.x.x/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gl' {
  declare module.exports: any;
}
