// flow-typed signature: 776dfa23938be195993fc0a10bdc85b6
// flow-typed version: <<STUB>>/glamor_v2.20.22/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

 declare module 'glamor' {
   declare module.exports: {
     css: (...styles: mixed[]) => {
       toString: () => string;
     },
     rehydrate: (string[]) => void,
   };
 }

declare module 'glamor/server' {
  declare module.exports: {
    renderStatic: (() => string) => {
      html: string,
      css: string,
      ids: string[],
    };
  };
}
