// flow-typed signature: 1556daa4b7c80c7b88574b34596adf36
// flow-typed version: <<STUB>>/graphql-server-hapi_v^0.6.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-server-hapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-server-hapi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-server-hapi/dist/hapiApollo' {
  declare module.exports: any;
}

declare module 'graphql-server-hapi/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-server-hapi/dist/hapiApollo.js' {
  declare module.exports: $Exports<'graphql-server-hapi/dist/hapiApollo'>;
}
declare module 'graphql-server-hapi/dist/index.js' {
  declare module.exports: $Exports<'graphql-server-hapi/dist/index'>;
}
