// flow-typed signature: f69763863e3f1ac17494e276084ed40f
// flow-typed version: <<STUB>>/hapi_v^16.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi' {
  declare module.exports: any;
}

