// flow-typed signature: f8332547d29ec988b42c63255800c2fe
// flow-typed version: <<STUB>>/jsverify_v0.7.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsverify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsverify' {
  declare module.exports: any;
}
