// flow-typed signature: d33596e3879ef1c5f46520c4c78ca48f
// flow-typed version: <<STUB>>/mapbox.js_v3.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox.js' {
  import type { Map, MapOptions } from 'leaflet';

  declare type L = $Exports<'leaflet'>;

  declare type StyleLayerOptions = {|
    accessToken?: string,
  |};

  declare class StyleLayer {
    addTo(map: Map): this,
  }

  declare type AttributionControlOptions = {
    compact?: boolean,
  }

  declare export type MapboxMapOptions = {|
    ...MapOptions,
    tileLayer?: mixed,
    featureLayer?: mixed,
    gridLayer?: mixed,
    legendControl?: mixed,
    shareControl?: mixed,
    accessToken?: string,
    attributionControl?: AttributionControlOptions,
  |}

  declare type mapbox = {
    map: (el: HTMLElement | string, tiles: mixed, options?: MapboxMapOptions) => Map,
    accessToken: string,
    styleLayer: (url: string, options?: StyleLayerOptions) => StyleLayer,
  }

  declare type LWithMapbox = {|
    ...L,
    mapbox: mapbox,
  |}

  declare module.exports: LWithMapbox
}
