// flow-typed signature: cb5a75696aa53c529af193b75cd778ad
// flow-typed version: <<STUB>>/mobx-utils_v2.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-utils' {
  declare type IPromiseBasedObservable<V> = {
    state: 'pending',
    promise: Promise<V>,
  } | {
    state: 'fulfilled',
    promise: Promise<V>,
    value: V,
  } | {
    state: 'rejected',
    promise: Promise<V>,
    value: any,
  };

  declare module.exports: {
    fromPromise: <V> (promise: Promise<V>) => IPromiseBasedObservable<V>
  };
}
