// flow-typed signature: 608a3a5994825cc76f5c263b0591e14f
// flow-typed version: <<STUB>>/redux-pack_v^0.1.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-pack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-pack' {
  declare module.exports: {
    middleware: Function,
    handle: <S>(state: S, action: { type: $Subtype<string> }, handlers: {|
      start?: (state: S) => S,
      finish?: (state: S) => S,
      failure?: (state: S) => S,
      success?: (state: S) => S,
      always?: (state: S) => S,
    |}) => S,
  };
}

