// flow-typed signature: 68ffa626a7c1b259f0b900904ae92891
// flow-typed version: <<STUB>>/redux-inject_v^1.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-inject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-inject/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-inject/lib/index.js' {
  declare module.exports: $Exports<'redux-inject/lib/index'>;
}
