// flow-typed signature: 0a6011243b4566f74f87da38bfaa9ea1
// flow-typed version: <<STUB>>/sinon_vx.x.x/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon' {
  declare module.exports: any;
}
