// flow-typed signature: a9926b77f9dad63d2e52fc7c020317ea
// flow-typed version: <<STUB>>/urlsearchparams_v0.1.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urlsearchparams'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urlsearchparams' {
  declare module.exports: {
    URLSearchParams: Class<URLSearchParams>,
  };
}
