dist: trusty
services:
- docker
language: node_js
node_js:
- 8
env:
- TZ=America/New_York
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@5.6.x
before_script:
- npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-update
script:
- npm run-script test-ci
after_script:
- npx codecov
- npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-upload
branches:
  only:
  - production
  - staging
  - "/^greenkeeper\\/.*$/"
before_deploy:
- pip install --upgrade --user awscli
deploy:
- provider: script
  script: "./deploy/deploy.sh $STAGING_CLUSTER_STACK $STAGING_APP_STACK $STAGING_REPOSITORY_NAME
    $STAGING_DESIRED_COUNT && ./deploy/deploy.sh $PROD_CLUSTER_STACK $PROD_APP_STACK $PROD_REPOSITORY_NAME
    $PROD_DESIRED_COUNT"
  on:
    branch: production
notifications:
  slack:
    rooms:
      secure: EOXQsyhbUHPWrfDjhB4XcRXeErVaNGMyyG46BB+Zlb/CzxH2A9LU+1l4stZJ/bEVqO2lYFmyM0N94zdrxNtoWPU0DbNbq0/zS7DEcPf9ehAfc/55SZ7PXP2RIdT7MLHrVrfigFjIUN3mJNjPnHRkjkcde0WDsW3374GIPPdo3KFL4MjsqpBIybAd5lcfBeEOCyUZWQMaSUhY2eWRGCvV7G9nXhnjhCP7fGWApSXCTlhKPkucMZHC074D5rfNwQH0rdQziMfv9VWKZK6s9Ok+J2GlmfZTtqj0SB93iNWn1FsWhy+xxuYAUrGfD4HTUuqnZI9IdC5kay3CjYWSNLsjez3+Y9Fa47HKOkE6OlWvfjiFpnTABjUkpxTzt22QARmQuN/qt4te7iEyUWlBVX9X/xSdKEH8DUbfJMKtMpQ5wVVmSZQO4yShSxF8Fynp5n87aXcY1oyrn3LI4KCEno16ubMbVU5hj6hU3pj+vCi84Exdiulinr+FDNoMpMtafELLByDMPMgPG/5oNBZB0IoDQ2TL4Jp1Kbeb8e6nhqAvFIPF7JqQG+8tVwQmfnHY2FqhdC+8UmF1QyQ3qLRl866Zz2nh2i7lrB1zUKWThC2R0Y+MCT0VQmHMCkTj8wKJrY69S9/P0CXVmsVEjAi2vYy9niHlJXqXpoTAcGoFco2vpV8=
