language: ruby
dist: trusty
group: edge
rvm:
- 2.4.0
deploy:
  provider: heroku
  app: cob-oemalerts
  on: master
  api_key:
    secure: NN2/QITclzWys5vSO2TtxTzXVSujRRbcSq58qxW+s5SfWgMrpF3fzTYDe5cPjyiYBoto8palLVBYtX2qUvxQs6DaKShvbcB7V0vDgD140m0kd2Xp86kkgAjpb68Fprf4hhi5rYYhI7uD07nUyLG1xtsyn4Bpvsnil1scLntMDUOxwAf8CnS6ATqHhyfKZBCqL3tQ8TUF/chdokQExjWMXyrg/34WDlLQL/plCjJBvv3xgK2ezXCLUVjz2YDX10/FCdmuRP8RvPT3SjfGMNu1dW12few4DqcyE2k80uTpuQv++6vj2SbdcPH1ceFiyjqcjCGetIQ/MUXZr5SqDPToNY90/enBlmBADI8OhZoegBbOGfH9selOSJYb7B3r06pP835aJqPIpoYDDqxik9lPN+Dgzg7VITgeGTl5D+mUarcANRxfk8B3kOAw8T+WxdkizujbB2qbPBdrbWePJW8KM47AGR05JyxUskcDnkaH1FU/yL/czIoiGGybfTWysKkn5+kB7RtERkarRXNrbHWp0QGa1cGYdM5/cWF7UeYpHpsReckLB9QU+ILxRkk4gGIWcGVw0+QRnpQMcwJeVjupudhhZO4E6NbY5CGkYRePkV7iNO2tYaz6u0JiXgRUNmEf86Nun8COt4+9hBQNrk1JWBw8GE7KdMxWQIXXeuz+ERQ=
notifications:
  slack:
    secure: b2UX5FnE2/C5MDNK47EP0GZIRmfwX+18HES0Q/uSwt6t7+ogKCtIjWCp1sIPd7jqRak0VmLoM0OHy6MBjz6x+1MQMNUqPEiO1f2APgBJ48c6rzeWQKTVfrKsUvPYIA+gxQ7jq7Gn0zPYQ5/+KXkxac+NrVoH85sI0xIL2BhFgQu1W4OlLLFKT11U7zJtCi3bcYhF7/eyCcrs3+IBGGp9sldjWvaVLDqUnFjz3c5AXwxlbJ6UTq7GIdIEe5Xw/UOJS9weedhoYH2XSNzFpmqqkAGcvkFpgCeYxf12iiqkmoAq5A0CxWVXqA3vG+imabuQonpbQsGdvtFP71EV9o9DxwATwxaGhBpX+Sw4zN7v25IC6n7rcvcK2F9dtY0CAb8BpWbEbWMDXXmVvFEVAvgARQ/b+L7YOJbNbbJwJQqZkllJp0lAFluyMDwpP2Ncr177S5hR/4Z6rlj1aLK1nhbmi/tK/kSNe+bcashm7/S2KG076hN0b5TB87hsbkvHsnVJDMKXSHwKrrdJiXDAkwZbl2sBp/bbfMTXyEqrINUG4WA70WXP3lR/QJy2pldVEYIU5rRwSzZ0BJ9raF7iiXFgTn3+Yhl0U/UgcDCEKoRvutM/suCy1mQBYP+Gv1uyFNFco37doQbPeyAXNb1vjfJQtyzy8I31gIN/sK590YxLBCA=
