language: ruby
dist: trusty
services:
- docker
rvm:
- 2.4.0
branches:
  only:
  - production
  - staging
before_deploy:
- pip install --upgrade --user awscli
deploy:
- provider: script
  script: "./deploy/deploy.sh $STAGING_CLUSTER_STACK $STAGING_APP_STACK $STAGING_REPOSITORY_NAME
    $STAGING_DESIRED_COUNT"
  on:
    branch: staging
- provider: script
  script: "./deploy/deploy.sh $PROD_CLUSTER_STACK $PROD_APP_STACK $PROD_REPOSITORY_NAME
    $PROD_DESIRED_COUNT"
  on:
    branch: production
notifications:
  slack:
    rooms:
      secure: dVPv78QG9xrCr5TnS9GdTGlZ0hcuWD8VWmRSLzi8/hSVOHO5VuThqxzTuSD/Ewne1XUds+w7NtrD4QAWq8+fl6fl41c0xvwD3TnKhk3gA5JVugeKwllJyoqLdDKdLf7VBPwB3zV+uOf9ytcyUbAhe8MXHZAK6xem5ExB/KqNZ/G4R8W4mAKnHTtTCDr6QmVHaLOfarMm4FWckWfyQGPRJhH0NQjrNSfHbv7CYhfLFKDxaCh0nnU/cddlaxx9Lv7+V64w1elJZXJSvUJ3f1m0he5aKQJ9W/uTfP6EVU5LzXah8wgHy6N5H+xvmWNXzhORyEHBBgwlXgp8dY/CS6N7H/rv3iTzKVfOAD0zzH3kYRIc05KVdx3O9MZHkf9RNXDHtyleHura//VJG/EOT8aV7z6ijg+1fcv678U0Bbu5LDdB+sewCMJfFQFm30s2kQJgiXc9wyPRrRlRzeoNB2+lHfoaeRIngxNQuyCZzvgSGRaVK24i1pCwPAscnOsTI4oTW2tCAbth64z9WSfG2kBqh52/O63eg8q7mIrt/c/EDu4ZQC4pWrB+hkKg2gkhiGwGfSagkXU/9ts8FdzXAP/iamujG7JIHv1MXhCNVjLmpip80K4sfeKC3cNQMfhKUVqFBliNjgvqe0fjFpdea7rs4ToGDHr0HQVxyDZIN82QBO0=
