version: 0.2

phases:
  install:
    commands:
      - npm config set scripts-prepend-node-path true
      - npm install -g yarn
  # TODO(finh): It would be neat to do container building as the build step and
  # service update as post_build.
  build:
    commands:
      - ./deploy/codebuild-deploy.sh
