version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node -v
      - npm config set scripts-prepend-node-path true
      - npm install -g yarn
  # TODO(finh): It would be neat to do container building as the build step and
  # service update as post_build.
  build:
    commands:
      - echo Re-Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - ./deploy/dockerHubRateLimit.sh
      - ./deploy/codebuild-deploy.sh
      - ./deploy/dockerHubRateLimit.sh
