// flow-typed signature: a1c5cf7783720b1e31d9395583bd43a1
// flow-typed version: <<STUB>>/postmark_v1.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postmark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postmark' {
  declare type Email = {|
    From: string,
    To: string,
    Cc?: string,
    Bcc?: string,
    Subject: string,
    Tag?: string,
    HtmlBody?: string,
    TextBody?: string,
    ReplyTo?: string,
    Headers?: Array<{|
      Name: string,
      Value: string,
    |}>,
    TrackOpens?: boolean,
    TrackLinks?: 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly',
    Attachments?: Array<{|
      Name: string,
      Content: string,
      ContentType: string,
    |}>,
  |};

  declare type SendEmailResult = {|
    To: string,
    SubmittedAt: string,
    MessageID: string,
    ErrorCode: number,
    Message: string,
  |};

  declare export class Client {
    constructor(serverApiToken: string): this;
    sendEmail(email: Email, cb?: (error: ?Error, result: SendEmailResult) => mixed): void;
  }
}
