import React from 'react';
import { storiesOf } from '@storybook/react';

// We do this from the snapshots generated by running the ReceiptEmail tests
// because we don't want to try and run the email templates in the browser.
//
// This snapshot parsing is taken from the jest-snapshots utils code. We need to
// use require rather than fs.readFile so that the snapshot gets webpack-bundled
// and we can run this client-side.
const SNAPSHOT_CONTENTS = require('./__snapshots__/EmailTemplates.test.ts.snap');
const SNAPSHOTS = {};
new Function('exports', SNAPSHOT_CONTENTS)(SNAPSHOTS);

function snapToString(name: string) {
  return JSON.parse(SNAPSHOTS[name].trim().replace(/\n/g, '\\n'));
}

storiesOf('Email/Death Receipt', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Death certificates 2'),
      }}
    />
  ))
  .add('text', () => <pre>{snapToString('receipt Death certificates 3')}</pre>);

storiesOf('Email/Birth Receipt', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Birth certificate 2'),
      }}
    />
  ))
  .add('text', () => <pre>{snapToString('receipt Birth certificate 3')}</pre>);

storiesOf('Email/Birth Shipped', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Birth certificate shipped 2'),
      }}
    />
  ))
  .add('text', () => (
    <pre>{snapToString('receipt Birth certificate shipped 3')}</pre>
  ));
