import React from 'react';
import { storiesOf } from '@storybook/react';

// We do this from the snapshots generated by running the ReceiptEmail tests
// because we don't want to try and run the email templates in the browser.
const SNAPSHOTS = require('./__snapshots__/EmailTemplates.test.ts.snap');

function snapToString(name: string) {
  return JSON.parse(SNAPSHOTS[name].trim().replace(/\n/g, '\\n'));
}

storiesOf('Email/Death/Receipt', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Death certificates 2'),
      }}
    />
  ))
  .add('text', () => <pre>{snapToString('receipt Death certificates 3')}</pre>);

storiesOf('Email/Birth/Receipt', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Birth certificate 2'),
      }}
    />
  ))
  .add('text', () => <pre>{snapToString('receipt Birth certificate 3')}</pre>);

storiesOf('Email/Birth/Shipped', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Birth certificate shipped 2'),
      }}
    />
  ))
  .add('text', () => (
    <pre>{snapToString('receipt Birth certificate shipped 3')}</pre>
  ));

storiesOf('Email/Birth/Expired', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('expired Birth certificate expired 2'),
      }}
    />
  ))
  .add('text', () => (
    <pre>{snapToString('expired Birth certificate expired 3')}</pre>
  ));

storiesOf('Email/Marriage/Receipt', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Marriage certificate 2'),
      }}
    />
  ))
  .add('text', () => (
    <pre>{snapToString('receipt Marriage certificate 3')}</pre>
  ));

storiesOf('Email/Marriage/Shipped', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('receipt Marriage certificate shipped 2'),
      }}
    />
  ))
  .add('text', () => (
    <pre>{snapToString('receipt Marriage certificate shipped 3')}</pre>
  ));

storiesOf('Email/Marriage/Expired', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('expired Marriage certificate expired 2'),
      }}
    />
  ))
  .add('text', () => (
    <pre>{snapToString('expired Marriage certificate expired 3')}</pre>
  ));
