import React from 'react';
import { storiesOf } from '@storybook/react';

// We do this from the snapshots generated by running the ReceiptEmail tests
// because we don't want to try and run the email templates in the browser.
//
// This snapshot parsing is taken from the jest-snapshots utils code. We need to
// use require rather than fs.readFile so that the snapshot gets webpack-bundled
// and we can run this client-side.
const SNAPSHOT_CONTENTS = require('./__snapshots__/ReceiptEmail.test.ts.snap');
const SNAPSHOTS = {};
new Function('exports', SNAPSHOT_CONTENTS)(SNAPSHOTS);

function snapToString(name: string) {
  return JSON.parse(SNAPSHOTS[name].trim().replace(/\n/g, '\\n'));
}

storiesOf('ReceiptEmail', module)
  .add('HTML', () => (
    <div
      dangerouslySetInnerHTML={{
        __html: snapToString('it renders an HTML body 1'),
      }}
    />
  ))
  .add('text', () => <pre>{snapToString('it renders a text body 1')}</pre>);
