version: '3'
services:
  registry-certs:
    image: local-dev/registry-certs:latest
    container_name: registry-certs
    ports:
      - 3000:3000
    working_dir: /app/services-js/registry-certs
    extra_hosts:
      - vtsql71.cityhall.boston.cob:10.241.129.43
    volumes:
      - ~/.aws:/root/.aws
    environment:
      AWS_S3_CONFIG_URL: s3://cob-digital-apps-staging-config/registry-certs
      DEPLOY_VARIANT: default
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_VERSION: 14.19.1
      YARN_VERSION: 1.22.17
      WORKSPACE: registry-certs
      NODE_ENV: production
      USE_SSL: true
    network_mode: bridge
