version: '3'
services:
  access-boston:
    image: local-test/access-boston:latest
    container_name: access-boston
    ports:
      - 3000:3000
    working_dir: /app/services-js/access-boston
    # extra_hosts:
    #   - [domain]:[IP]
    volumes:
      - ~/.aws:/root/.aws
    environment:
      AWS_S3_CONFIG_URL: s3://cob-digital-apps-staging-config/access-boston
      DEPLOY_VARIANT: default
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_VERSION: 14.19.1
      YARN_VERSION: 1.22.17
      WORKSPACE: access-boston
      NODE_ENV: production
      USE_SSL: 1
    network_mode: bridge
