import React from 'react';
import { storiesOf } from '@storybook/react';

// We do this from the snapshots generated by running the tests
// because we don't want to try and run the email templates in the browser.
//
// This snapshot parsing is taken from the jest-snapshots utils code. We need to
// use require rather than fs.readFile so that the snapshot gets webpack-bundled
// and we can run this client-side.
//
// taken from registry-certs project -jess 10/18/18
const SNAPSHOT_CONTENTS = require('./__snapshots__/EmailContent.test.ts.snap');
const SNAPSHOTS = {};
new Function('exports', SNAPSHOT_CONTENTS)(SNAPSHOTS);

function snapToString(name: string) {
  return JSON.parse(SNAPSHOTS[name].trim().replace(/\n/g, '\\n'));
}

storiesOf('EmailContent', module)
  .add('applicant emails', () => (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: snapToString('Renders email body applicant HTML 1'),
        }}
      />

      <pre>{snapToString('Renders email body applicant text 1')}</pre>
    </>
  ))
  .add('policy office emails', () => (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: snapToString('Renders email body policy office HTML 1'),
        }}
      />

      <pre>{snapToString('Renders email body policy office text 1')}</pre>
    </>
  ));
