language: node_js
node_js:
  - "node"

deploy:
  provider: heroku
  app: cob-311
  api_key:
    secure: fEjoKeRP0MTvT5V8taQly1Wmfjg5nW3OtkflD+Q1ijzQnFMKOUqvaimBuRFHk+Aqtf08oHhfS8bQlaONVgU7NTa9LcR+GG6UWMMW9PSk0ig4JNpSZhfK/ViLzWN+0jEygG9CL8cojYUY3x5RwdtptdL2kWjTeu1oZ9t3Nw+97yZl64tWbSUkB1RIvizLYhTylaGCcWRfJmfG7bZqxHEsJEgOlxhBnKKIm67Bk8I3CoIesBF5MQ+xK42+yPUwurFr1ZA2o7rxs40GqxeOGikNeGbEcTeDSa9RbAoygoYWyIT2qP+BVTUYInOZ89tX3N7YfWr/f6aivMxejxrY5Wz2BaWypdzPOInY12qIoKRCSqVco0ekFoEPIJF9nBaBlQb8zGhsDeB0ywxnSs1Mxbrc3bcpAarXGyzOctHKVyaUWV1aFv3s0RBADHjk3ph7ZvfoPtKi0TjoR4mMZmhabLiDdTovcq51olERBGLHra2bu9smJhFM+CgJ4yf50LAl9LzFBjvTfcTAwHngWSwUfiUKnotr3liTaGRxqPtvY6nyYyKkxcXA2PyRGh2WDRW9HOXGvdFJS9qSbtLSKqUhsr2krsnemtPcIpcq1RGEZaJlRPlrpezL/utT5teere7vqXQUCG6Kxf7uNpWSS4Y0f+JRKkK2E6DFhKDIe7X5prcPiT4=
  on: master
