version: '2'
services:
  service:
    image: "${SERVICE_IMAGE}"
    environment:
      NODE_ENV: production
      # Used by script/entrypoint.sh to download our .env configuration
      AWS_S3_CONFIG_URL: "${AWS_S3_CONFIG_URL}"
    mem_reservation: 209715200 # 200mb in bytes
    mem_limit: 524288000 # 500mb in bytes
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_DEFAULT_REGION}"
        awslogs-group: "${AWS_CLOUDWATCH_LOGS_GROUP}"
        awslogs-stream-prefix: "${AWS_CLOUDWATCH_LOGS_PREFIX}"
